version: "3"
services:
    flask:
        environment: 
            - FLASK_ENV=development
            - FLASK_APP=main.py
        build:
            context: ./backend
        container_name: flask
        depends_on: 
            - db
        networks:
            main_network:
                ipv4_address: 172.29.1.1
    db:
        container_name: mongo
        image: mongo
        networks:
            - main_network
    react:
        build:
            context: ./frontend
        container_name: react
        stdin_open: true
        depends_on: 
            - flask
        networks:
            - main_network

networks:
  main_network:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16