version: "3"
services:
    flask:
        build:
            dockerfile: Dockerfile
            context: .
        container_name: flask
        ports:
            - "5000:5000"
    db:
        image: mongo